-- ------------------------------------------------------------------------
-- streams_and_tasks.sql
-- ADR-0019 -- Snowflake-native trigger gate (Streams + Triggered Tasks)
--
-- Replaces the polling in bronze_new_data_sensor (which queried
-- MAX(RECORD_METADATA:CreateTime) across the 19+1 Bronze tables every 60s,
-- colliding with AUTO_SUSPEND=60s and keeping the warehouse effectively
-- always on -- the original problem of this analysis).
--
-- How it works:
--   1. One STREAM per Bronze table tracks changes (append-only, since
--      Snowpipe only INSERTs into those tables).
--   2. One TASK per domain, scheduled every 1 minute, with
--      WHEN SYSTEM$STREAM_HAS_DATA(...) -- that evaluation is done by
--      Snowflake's control plane and does NOT consume the warehouse when
--      the result is FALSE. Only when there is new data does the task
--      actually fire, consuming the warehouse for the minimum needed.
--   3. Structural advantage over an external watcher (Kafka): the STREAM is
--      defined over the real Bronze TABLE. It can only report "has data"
--      after Snowpipe has committed the row -- eliminating by construction
--      the "Kafka published but Snowflake has not materialized yet" gap
--      identified in the watcher architecture analysis (it is not a
--      debounce heuristic, it is a structural guarantee).
--   4. The task writes to CONFIG.PENDING_RUNS, which the Dagster sensor
--      (see sensors.py) then queries -- 1 light SELECT instead of
--      19-20 SELECT MAX(...) per cycle.
--
-- Prerequisite (run once as ACCOUNTADMIN):
--   GRANT EXECUTE TASK ON ACCOUNT TO ROLE CDC_ROLE;
--
-- NOT TESTED LIVE -- no active Snowflake was available during this analysis.
-- Run it in a test environment before any client demo.
-- ------------------------------------------------------------------------

USE ROLE CDC_ROLE;
USE DATABASE CDC_POC;

-- -- Control tables -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CONFIG.PENDING_RUNS (
    domain      STRING,
    detected_at TIMESTAMP_NTZ,
    consumed    BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CONFIG.STREAM_CONSUMPTION_LOG (
    domain       STRING,
    rows_seen    NUMBER,
    consumed_at  TIMESTAMP_NTZ
);

-- -- Shared stored procedure (DRY -- 1 proc for all domains) ------------

CREATE OR REPLACE PROCEDURE CONFIG.SP_GATE_DOMAIN(STREAM_FQN STRING, DOMAIN_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFIG.PENDING_RUNS (domain, detected_at, consumed)
    SELECT :DOMAIN_NAME, CURRENT_TIMESTAMP(), FALSE;

    EXECUTE IMMEDIATE
        'INSERT INTO CONFIG.STREAM_CONSUMPTION_LOG (domain, rows_seen, consumed_at) ' ||
        'SELECT ''' || :DOMAIN_NAME || ''', COUNT(*), CURRENT_TIMESTAMP() FROM ' || :STREAM_FQN;

    RETURN 'OK: ' || :DOMAIN_NAME;
END;
$$;

-- -- Streams + Tasks -- 1 pair per Bronze domain (v6: only the 10 Tier 1, ADR-0022) ------------------------

-- ORDERS
CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM ON TABLE BRONZE.ORDERS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.ORDERS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.ORDERS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.ORDERS_STREAM', 'ORDERS');

ALTER TASK BRONZE.ORDERS_GATE_TASK RESUME;

-- DRIVERS
CREATE OR REPLACE STREAM BRONZE.DRIVERS_STREAM ON TABLE BRONZE.DRIVERS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.DRIVERS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.DRIVERS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.DRIVERS_STREAM', 'DRIVERS');

ALTER TASK BRONZE.DRIVERS_GATE_TASK RESUME;

-- DRIVER_SHIFTS
CREATE OR REPLACE STREAM BRONZE.DRIVER_SHIFTS_STREAM ON TABLE BRONZE.DRIVER_SHIFTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.DRIVER_SHIFTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.DRIVER_SHIFTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.DRIVER_SHIFTS_STREAM', 'DRIVER_SHIFTS');

ALTER TASK BRONZE.DRIVER_SHIFTS_GATE_TASK RESUME;

-- RESTAURANTS
CREATE OR REPLACE STREAM BRONZE.RESTAURANTS_STREAM ON TABLE BRONZE.RESTAURANTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.RESTAURANTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.RESTAURANTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.RESTAURANTS_STREAM', 'RESTAURANTS');

ALTER TASK BRONZE.RESTAURANTS_GATE_TASK RESUME;

-- USERS_MONGO
CREATE OR REPLACE STREAM BRONZE.USERS_MONGO_STREAM ON TABLE BRONZE.USERS_MONGO
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.USERS_MONGO_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.USERS_MONGO_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.USERS_MONGO_STREAM', 'USERS_MONGO');

ALTER TASK BRONZE.USERS_MONGO_GATE_TASK RESUME;

-- USERS_MSSQL
CREATE OR REPLACE STREAM BRONZE.USERS_MSSQL_STREAM ON TABLE BRONZE.USERS_MSSQL
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.USERS_MSSQL_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.USERS_MSSQL_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.USERS_MSSQL_STREAM', 'USERS_MSSQL');

ALTER TASK BRONZE.USERS_MSSQL_GATE_TASK RESUME;

-- ORDER_ITEMS
CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM ON TABLE BRONZE.ORDER_ITEMS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.ORDER_ITEMS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.ORDER_ITEMS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.ORDER_ITEMS_STREAM', 'ORDER_ITEMS');

ALTER TASK BRONZE.ORDER_ITEMS_GATE_TASK RESUME;

-- PAYMENT_EVENTS
CREATE OR REPLACE STREAM BRONZE.PAYMENT_EVENTS_STREAM ON TABLE BRONZE.PAYMENT_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.PAYMENT_EVENTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.PAYMENT_EVENTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.PAYMENT_EVENTS_STREAM', 'PAYMENT_EVENTS');

ALTER TASK BRONZE.PAYMENT_EVENTS_GATE_TASK RESUME;

-- RECOMMENDATIONS
CREATE OR REPLACE STREAM BRONZE.RECOMMENDATIONS_STREAM ON TABLE BRONZE.RECOMMENDATIONS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.RECOMMENDATIONS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.RECOMMENDATIONS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.RECOMMENDATIONS_STREAM', 'RECOMMENDATIONS');

ALTER TASK BRONZE.RECOMMENDATIONS_GATE_TASK RESUME;

-- SEARCH_EVENTS
CREATE OR REPLACE STREAM BRONZE.SEARCH_EVENTS_STREAM ON TABLE BRONZE.SEARCH_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.SEARCH_EVENTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.SEARCH_EVENTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.SEARCH_EVENTS_STREAM', 'SEARCH_EVENTS');

ALTER TASK BRONZE.SEARCH_EVENTS_GATE_TASK RESUME;

-- -- Verification ---------------------------------------------------------
-- Confirm the tasks are active (not SUSPENDED):
-- SHOW TASKS IN SCHEMA BRONZE;
--
-- Confirm the execution history (it should only have rows when there was
-- genuinely new data -- if it shows a run every 1 min with no traffic,
-- something is wrong and SYSTEM$STREAM_HAS_DATA is not working as
-- expected):
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
--     SCHEDULED_TIME_RANGE_START => DATEADD('hour', -6, CURRENT_TIMESTAMP())
-- )) ORDER BY SCHEDULED_TIME DESC;
