-- ------------------------------------------------------------------------
-- streams_and_tasks.sql
-- ADR-0019 -- Gate de disparo nativo do Snowflake (Streams + Triggered Tasks)
--
-- Substitui o polling do bronze_new_data_sensor (que consultava
-- MAX(RECORD_METADATA:CreateTime) nas 19+1 tabelas Bronze a cada 60s,
-- colidindo com AUTO_SUSPEND=60s e mantendo o warehouse praticamente
-- sempre ligado -- o problema original desta analise).
--
-- Como funciona:
--   1. Um STREAM por tabela Bronze rastreia mudancas (append-only, ja que
--      o Snowpipe so faz INSERT nessas tabelas).
--   2. Uma TASK por dominio, agendada a cada 1 minuto, com
--      WHEN SYSTEM$STREAM_HAS_DATA(...) -- essa avaliacao e feita pelo
--      control plane do Snowflake e NAO consome o warehouse quando o
--      resultado e FALSE. So quando ha dado novo a task efetivamente
--      dispara, consumindo o warehouse pelo minimo necessario.
--   3. Vantagem estrutural sobre um watcher externo (Kafka): o STREAM e
--      definido sobre a TABELA Bronze real. Ele so pode indicar "tem
--      dado" depois que o Snowpipe ja commitou a linha -- elimina por
--      construcao o gap de "Kafka publicou mas Snowflake ainda nao
--      materializou" identificado na analise da arquitetura do watcher
--      (nao e uma heuristica de debounce, e uma garantia estrutural).
--   4. A task grava em CONFIG.PENDING_RUNS, que o sensor Dagster
--      (ver sensors.py) passa a consultar -- 1 SELECT leve em vez de
--      19-20 SELECT MAX(...) por ciclo.
--
-- Pre-requisito (rodar uma vez como ACCOUNTADMIN):
--   GRANT EXECUTE TASK ON ACCOUNT TO ROLE CDC_ROLE;
--
-- NAO TESTADO AO VIVO -- nao ha Snowflake ativo disponivel durante esta
-- analise. Rode em ambiente de teste antes de qualquer demo de cliente.
-- ------------------------------------------------------------------------

USE ROLE CDC_ROLE;
USE DATABASE CDC_POC;

-- -- Tabelas de controle -----------------------------------------------

CREATE TABLE IF NOT EXISTS CONFIG.PENDING_RUNS (
    domain      STRING,
    detected_at TIMESTAMP_NTZ,
    consumed    BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CONFIG.STREAM_CONSUMPTION_LOG (
    domain       STRING,
    rows_seen    NUMBER,
    consumed_at  TIMESTAMP_NTZ
);

-- -- Stored procedure compartilhada (DRY -- 1 proc para os 20 dominios) --

CREATE OR REPLACE PROCEDURE CONFIG.SP_GATE_DOMAIN(STREAM_FQN STRING, DOMAIN_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CONFIG.PENDING_RUNS (domain, detected_at, consumed)
    SELECT :DOMAIN_NAME, CURRENT_TIMESTAMP(), FALSE;

    EXECUTE IMMEDIATE
        'INSERT INTO CONFIG.STREAM_CONSUMPTION_LOG (domain, rows_seen, consumed_at) ' ||
        'SELECT ''' || :DOMAIN_NAME || ''', COUNT(*), CURRENT_TIMESTAMP() FROM ' || :STREAM_FQN;

    RETURN 'OK: ' || :DOMAIN_NAME;
END;
$$;

-- -- Streams + Tasks -- 1 par por dominio Bronze (v6: so os 10 Tier 1, ADR-0022) --------------------------

-- ORDERS
CREATE OR REPLACE STREAM BRONZE.ORDERS_STREAM ON TABLE BRONZE.ORDERS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.ORDERS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.ORDERS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.ORDERS_STREAM', 'ORDERS');

ALTER TASK BRONZE.ORDERS_GATE_TASK RESUME;

-- DRIVERS
CREATE OR REPLACE STREAM BRONZE.DRIVERS_STREAM ON TABLE BRONZE.DRIVERS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.DRIVERS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.DRIVERS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.DRIVERS_STREAM', 'DRIVERS');

ALTER TASK BRONZE.DRIVERS_GATE_TASK RESUME;

-- DRIVER_SHIFTS
CREATE OR REPLACE STREAM BRONZE.DRIVER_SHIFTS_STREAM ON TABLE BRONZE.DRIVER_SHIFTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.DRIVER_SHIFTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.DRIVER_SHIFTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.DRIVER_SHIFTS_STREAM', 'DRIVER_SHIFTS');

ALTER TASK BRONZE.DRIVER_SHIFTS_GATE_TASK RESUME;

-- RESTAURANTS
CREATE OR REPLACE STREAM BRONZE.RESTAURANTS_STREAM ON TABLE BRONZE.RESTAURANTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.RESTAURANTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.RESTAURANTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.RESTAURANTS_STREAM', 'RESTAURANTS');

ALTER TASK BRONZE.RESTAURANTS_GATE_TASK RESUME;

-- USERS_MONGO
CREATE OR REPLACE STREAM BRONZE.USERS_MONGO_STREAM ON TABLE BRONZE.USERS_MONGO
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.USERS_MONGO_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.USERS_MONGO_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.USERS_MONGO_STREAM', 'USERS_MONGO');

ALTER TASK BRONZE.USERS_MONGO_GATE_TASK RESUME;

-- USERS_MSSQL
CREATE OR REPLACE STREAM BRONZE.USERS_MSSQL_STREAM ON TABLE BRONZE.USERS_MSSQL
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.USERS_MSSQL_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.USERS_MSSQL_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.USERS_MSSQL_STREAM', 'USERS_MSSQL');

ALTER TASK BRONZE.USERS_MSSQL_GATE_TASK RESUME;

-- ORDER_ITEMS
CREATE OR REPLACE STREAM BRONZE.ORDER_ITEMS_STREAM ON TABLE BRONZE.ORDER_ITEMS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.ORDER_ITEMS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.ORDER_ITEMS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.ORDER_ITEMS_STREAM', 'ORDER_ITEMS');

ALTER TASK BRONZE.ORDER_ITEMS_GATE_TASK RESUME;

-- PAYMENT_EVENTS
CREATE OR REPLACE STREAM BRONZE.PAYMENT_EVENTS_STREAM ON TABLE BRONZE.PAYMENT_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.PAYMENT_EVENTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.PAYMENT_EVENTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.PAYMENT_EVENTS_STREAM', 'PAYMENT_EVENTS');

ALTER TASK BRONZE.PAYMENT_EVENTS_GATE_TASK RESUME;

-- RECOMMENDATIONS
CREATE OR REPLACE STREAM BRONZE.RECOMMENDATIONS_STREAM ON TABLE BRONZE.RECOMMENDATIONS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.RECOMMENDATIONS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.RECOMMENDATIONS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.RECOMMENDATIONS_STREAM', 'RECOMMENDATIONS');

ALTER TASK BRONZE.RECOMMENDATIONS_GATE_TASK RESUME;

-- SEARCH_EVENTS
CREATE OR REPLACE STREAM BRONZE.SEARCH_EVENTS_STREAM ON TABLE BRONZE.SEARCH_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK BRONZE.SEARCH_EVENTS_GATE_TASK
    WAREHOUSE = CDC_WH
    SCHEDULE  = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.SEARCH_EVENTS_STREAM')
AS
    CALL CONFIG.SP_GATE_DOMAIN('BRONZE.SEARCH_EVENTS_STREAM', 'SEARCH_EVENTS');

ALTER TASK BRONZE.SEARCH_EVENTS_GATE_TASK RESUME;

-- -- Verificacao ----------------------------------------------------------
-- Confirma que as 20 tasks estao ativas (nao SUSPENDED):
-- SHOW TASKS IN SCHEMA BRONZE;
--
-- Confirma historico de execucao (so deve ter linhas quando havia dado
-- novo de verdade -- se aparecer executando a cada 1 min mesmo sem
-- trafego, algo esta errado e o SYSTEM$STREAM_HAS_DATA nao esta
-- funcionando como esperado):
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
--     SCHEDULED_TIME_RANGE_START => DATEADD('hour', -6, CURRENT_TIMESTAMP())
-- )) ORDER BY SCHEDULED_TIME DESC;
